[package]
name = "jolt"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A note taking web-app"
repository = "https://github.com/NewDawn0/jolt"

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.94"
oiler = { git = "https://github.com/NewDawn0/oiler", version = "0.1.0" }
wasm-bindgen = "0.2.117"
web-sys = { version = "0.3.94", features = [
  "Window",
  "Document",
  "Element",
  "HtmlCanvasElement",
] }
