# Build tasks
[tasks.build]
description = "Build wasm and move to public"
dependencies = ["clean-files", "build-rust"]
command = "mv"
args = ["pkg", "public"]

[tasks.build-rust]
private = true
command = "wasm-pack"
args = ["build", "--target", "web"]
install_crate = "wasm-pack"

# Cleanup
[tasks.clean]
description = "Clean build artifacts"
dependencies = ["clean-files"]

[tasks.clean-files]
private = true
script = ["rm -rf pkg public/pkg"]

# Documentation
[tasks.doc]
description = "Build and open docs"
args = ["doc", "--open"]
command = "cargo"

# Formatting
[tasks.format]
description = "Format project"
args = ["fmt", "--", "--emit=files"]
command = "cargo"
install_crate = "rustfmt"

# Watching
[tasks.watch]
description = "Watch and serve"
run_task = { name = ["serve", "watch-build"], parallel = true }

[tasks.watch-build]
description = "Watch source and rebuild"
install_crate = "cargo-watch"
command = "cargo"
args = [
  "watch",
  "-w",
  "src",
  "-w",
  "public",
  "-i",
  "public/pkg",
  "-x",
  "make build",
]

# Serving
[tasks.serve]
description = "Serve public folder"
# @BUG: Rust webservers I've tried have a weird caching issue where by old versions are served
# Ive tried static-web-server & cargo-serve
command = "npx"
args = ["serve", "public"]
